version: '3.8'
services:
  duty-army-back:
        image: exam-back-img
        restart: always
        ports:  
          - "3004:3004"
        env_file:
          - .env
        extra_hosts:
          - "db.aja.local:192.168.70.3"